language: java
jdk:
- oraclejdk12
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  file: target/ClassFinder.jar
  on:
    tags: true
dd:
  secure: b41fGwWpJ3a5TUC1nqtDD7j1jmFmNVqhu2j/uXstW5QrpnQ7Q2ah81YOMAyxx4hWK7De72RRaEsgfsEnogDHY+Q3oN09w6gNFmN69nGrjiWbkiWVAHjMAQUgndorFJXzbDAWqt0a53EDsrOtf7zj1by1lJoMoVbuH3QJlSy8Te06tAVglC5d+C82TmHPPLMhuhBlAjoAPcM9BZlyFngYQ7UfCPt5NVceHKtXvAfR1dwthxngMZWxBQU6pRzz5aHQLWR226x5j9jFGAbGdfTirhK5CIfUcpl4E5J0lecgQ+d5Z14smsctdGDDCHRHRF+wsrC/iXk4PMNzTP4xWB+/Wh/PJ4JWoGhIqVAemHyXI6tvDpDhNbqUWEhwlpHLlKJevfVqD0+Up1LDgdZWeAB/jJgeuc4XkdbP03InpCKpjJpb+y1G655+CLn/AEASzX1mrMlfYyYLgWXe8jzaHhXOTpHE2uYbCaeMHbI4UIim7cynJGqbDCE6RxuzZ7ukHlb5u1ESwWXYdvDyg0nJ/4bwX9Lhc0QQgXGjYZp8OmZUCybKmoam5Ujo17KM8RwWyV7UXuMUKD/Zhk/JHsLGKJsy8NrRfiz+LWw3ZaEYM9wBceap5pbH2yohC/acgk24E5kWTGEOfbDzCsVBpJF2jDw2ft7V01o4z5g072NE8rPyPr4=
