language: java
jdk:
- oraclejdk12
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: zmrYPVKIcMfFEN3GPJq6DIuirNen1ppO+DoIqQwPEwjvMQQM8beC/Zz3f4ezKHaiD0k6PuDdpoysAjgNnbPv0dRxNE9BDOxGV0bll4yCuBnReyCuwrXulGEc8upkW+Xuoyjb2e0+R1hYpGh2ecbL76LBtKrwbW5MgCo1SXzuHemhCaKkQv7rHrXA27/LVyw0oaEqCyoDa585vvygWdbrByl2Smd4Jw9ikl4Soc1KaK8vGGIn5qXi+AiqfkN91sJ2nNF7PQUZUJshUtMMoLT0Hhv1znLl2ONsx30+TPnFXx/m51z36WVsOvhr0eZVQEcitEVPWndL2DGGSGrHfYH5lP2GpK45eKQo3Tn9eezXGIgaMLCbnHtKZSR3EdTODQkLzDUxe/zyNTWdzfloUeqAhwerIuN0/PVT5VkiBTQ4ByDLyOXjqkvrPTxhhfbRJeBof9WFPCIrukTxoig5eEp+w9tc5xD7/lHKLxWcC3Ze7Mz08yCBUGedeBe1I4J8Ih28jIgJtgrYgT3ceeznUP6e6lBzIW74qYRa0C2LJwoUlkohc2Ugb4paa8dOP/YQuOIGPyk+6kiRh21PHV9FP3c1i/G1wVlbMUUgUvdgBvH7es7sv/bNmp+u46lB85dfrBrhWVRDdu3RhVTVgETUcg8F8vzl2lFq4cw0ftlG3a5FMeU=
  file: target/ClassFinder.jar
  on:
    tags: true
dd:
  secure: h6wy+RgMbg1AJDYg01Vffo95dZN7nnnUxUIE8wBsSXrPuhA0sIgYbhzTCI9gBSGmHgdoYl/x8KfO2KZzTVsYGoJB4LaCcPD482TJDMJjyxLWqWNsDYtdyiFOTqBMlllvmwrb3LuN0knV/XaNt57isopqx3tOkgGawkCfIJPbGVCXYpMf+nYOdfHk3O2Z1x3kR+MCCh6k9+BhdbDNE8kjORMwgbvmjcRl0dzo7CI2uPsmEz7gpAuaBJeXVJ7tJCL0nTzGmr2NFEr3xWhBBZt13XUW68paSu5p9t1TnqVVnM3g465Y0znTleygmR10X5V82GcbjCeAudF2TCiGKDDAXAtRQomu9+tFsfmxmU/9qj5Nnb4EitSy6e2npeRq/x5iFL5dACJQLE4p9Odc3ud9fBa//IZMXOEET9AjjwqSKxH/ub3UsUg7SxmDbK+ILX88XgsO+fiikoMtbJPmh5lL65pT5h1HeKzVPExcnA8yxEwZ7hpAEXdeQx+x3BWEivBcd6WlSOyGAHiutbddl+OGZzladdx2CYdelvKLPQhYPMHaJvvCqQDIo6/C2+lIsDvgay1bO8ubkBhVfJR/dPnI1PoPB/Vx3CXtCj20q8a0fvFvmKQVRCXNHeuQbp1o7lwkcaj+N/4Km1Cze+b3F1scwwjR/qd410Vp/dmRI+Vv22Q=
