language: java
jdk:
- oraclejdk8
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: uiBmG6mvYYx6PmLBVN84AizA4oeEetVqPZ4Q+Fd0J+Ol0jC7jWCLxw6S5TK8d8Yr+bZ+N02Rjn4A0xLm4nGuI1mjvshJuVbdrCy7f4VpsAzg1x3bYpYRgAd4CDlwVIlYlR0CWQ6d98BtdLKfSoNnkEtwAKIexdFfpEAZ2x/Sc5CnxoLmJZG+M6Kt+D9ZFd18CMy83NUzP1zyy3yW6tg0eqccLMATX79f1MDhHNB+jSSXY2LktpueIEUcjwCOIsD6Zea7VakYegJaC1yU756S2eLuJE7gRLJjZAaCLCk9nrMcsApv2nshii/L6yEqRCL++ee6U2C7/KvAgo7oiadVs9bW315EHJvRhtLuaDwuvBv/2oqzIUG13/OvDBCDdumZD6LTt9rfiWYuB29MArQfGlnKSE9kEvmJAxhmT4yioJjK63DLZ8nXsnpDIGzxZSoU1whewNr0LTWIeCT9/wxHhLW3Qj5b//QxTzFf0WKsyJumuRju0c2XJajpIcbg1VvFaYUPlgOWdj54q40+0qIZLIyCzjYGEtcgkcIY6HRF5DytiZcYIWJS09l3sow+1tYgkRO6ZiMAo5JeQ39xxzQTmhCvt3rDoyml4acyZih45T5cYVkkq7AN2EaJrTboeLjPxAYtgbP/8jx5LdluPvFpE5y7/kMlvHVNGm/ZCCh2rW0=
  file: target/ClassFinder.jar
  on:
    tags: true
  
