language: java
jdk:
- oraclejdk12
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  file: target/ClassFinder.jar
  on:
    tags: true
  api_key:
    secure: pz8Gm3nOmtdeIzsG9VRxlTreCmVByH1h7LKeaHCsbJsFeoPePNc6qZCZXvBS/XEfv/wxo01RW2WgibwJ008ollbZCpu0D/jrLu43nCbbqY5APRbdJI3vCUMA9jkf0sMv4PgNPb+Gm0LTyzG1USS8dBD2SuZPB3BWewKvZ4iBq5TS9mAj+A7f/fTpl9oqkzUpdTnfHjfWfvB+UomAWuaa1MMpa/5NszojQ1iKSCFUDKP3pzZee3x3eW/+7nt1DUETSP8lX8EiS0vRO+aP0Z6jQ4QwLGvSQnJ0vR24UOnHdL8wYOHnYBMRAbEy/+t7oc6Rgi5W2CmFWPnU8JAmvuaPcOIBL8e/4OhJX4uFJjyNmD4bbYrFkUwjxgKo8W4uE/H51midZLXRYqnCdLit4ef8Ek206sOvVAjeFLiSJ4AxRdvADb1oLE8RwwNHnCWA1nVQUzJf5s9VrPfH1d+Qfw3PPldKRPswh8cp8pLwFi7EGgD9CR8fe7MfcElBHTkucKedxfco29rAxJDlvjZ7A/wGwVpZ0M3yyzoZMm8MXQMRBF7UfEhwH9NpGUWe+gPICp81F4K+Nibwxc6AIzaPoiCcJmW3DdqEd9V4Zp+Qq3hBOFzuiHmbO8wuHgEimEzxJxvBP6j7OdKI+Dnt+Vg88+8rAgKvVhVWuIQwbw8gpsPNGkk=
