language: java
jdk:
- oraclejdk12
branches:
  only:
  - "/^v.+/"
  - master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: zmrYPVKIcMfFEN3GPJq6DIuirNen1ppO+DoIqQwPEwjvMQQM8beC/Zz3f4ezKHaiD0k6PuDdpoysAjgNnbPv0dRxNE9BDOxGV0bll4yCuBnReyCuwrXulGEc8upkW+Xuoyjb2e0+R1hYpGh2ecbL76LBtKrwbW5MgCo1SXzuHemhCaKkQv7rHrXA27/LVyw0oaEqCyoDa585vvygWdbrByl2Smd4Jw9ikl4Soc1KaK8vGGIn5qXi+AiqfkN91sJ2nNF7PQUZUJshUtMMoLT0Hhv1znLl2ONsx30+TPnFXx/m51z36WVsOvhr0eZVQEcitEVPWndL2DGGSGrHfYH5lP2GpK45eKQo3Tn9eezXGIgaMLCbnHtKZSR3EdTODQkLzDUxe/zyNTWdzfloUeqAhwerIuN0/PVT5VkiBTQ4ByDLyOXjqkvrPTxhhfbRJeBof9WFPCIrukTxoig5eEp+w9tc5xD7/lHKLxWcC3Ze7Mz08yCBUGedeBe1I4J8Ih28jIgJtgrYgT3ceeznUP6e6lBzIW74qYRa0C2LJwoUlkohc2Ugb4paa8dOP/YQuOIGPyk+6kiRh21PHV9FP3c1i/G1wVlbMUUgUvdgBvH7es7sv/bNmp+u46lB85dfrBrhWVRDdu3RhVTVgETUcg8F8vzl2lFq4cw0ftlG3a5FMeU=
  file: target/ClassFinder.jar
  on:
    tags: true

