/**
 * 
 */
package jars.search.core;

/**
 * Logic exception: invalid regular expression
 */
public class PatternException extends Exception {

	//---------------------------------------------------------
	// Class constants 
	
	/**
	 * Generated by eclipse to avoid serialization problems.
	 */
	private static final long serialVersionUID = 2393808629067814039L;

	//---------------------------------------------------------
	// Class methods 
	
	/**
	 * Creates a PatternException with a given message
	 */
	public PatternException(String message) {
		super(message);
	}
}
