/**
 * 
 */
package jars.search.core;

/**
 * Core exception, wrapping every possible problem returned by the library
 */
public class SearchException extends Exception {

	/**
	 * Generated by Eclipse for serialization
	 */
	private static final long serialVersionUID = -4403745118131037445L;

	/**
	 * Creates an empty exception.
	 */
	public SearchException() {
		super();
	}

	/**
	 * Creates an exception wrapping a cause, with a customized message.
	 * @param msg Message
	 * @param ex Wrapped cause
	 */
	public SearchException(String msg, Throwable ex) {
		super(msg, ex);
	}

	/**
	 * Creates an exception with a customized message.
	 * @param msg Message
	 */
	public SearchException(String msg) {
		super(msg);
	}

	/**
	 * Creates an exception wrapping its cause
	 * @param ex Wrapped cause
	 */
	public SearchException(Throwable ex) {
		super(ex);
	}

	
}
